### ISSUE TITLE
Multiple configuration flags ignored

### ISSUE THREAD

**Issue by chrisgoddard** [memgraph/memgraph-platform#32]
Some context - I'm building a custom Docker image on top of memgraph-platform:latest so I can install some additional python dependencies. 

I'm specifying two configuration options in the environment variable:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/4922472/209879314-e6ddd728-69d2-4a38-abf5-8e421f8b0208.png">

What's weird is it will load whichever flag is set first (in this case the modules directory - but it ignores the second (or any additional) flags. Am I missing something really obvious?

**Comment by chrisgoddard** [comment]
It's also strange that I don't see a configuration file being generated at `/etc/memgraph/memgraph.conf` as is in the documentation.

**Comment by matea16** [comment]
Hi @chrisgoddard, thanks for reporting this, I managed to reproduce the bug.

While building Memgraph with docker and using the [Docker Compose for Memgraph Platform image](https://memgraph.com/docs/memgraph/reference-guide/deployment/docker#docker-compose-for-memgraph-platform-image), the second flag is ignored.

Also, after running the following docker commands:
docker run -it -p 7687:7687 -p 3000:3000 -p 7444:7444 -e MEMGRAPH="--log-level=TRACE" memgraph/memgraph-platform works as expected, but the same command with two parameters:
docker run -it -p 7687:7687 -p 3000:3000 -p 7444:7444 -e MEMGRAPH="--storage-properties-on-edges=TRUE --log-level=TRACE" memgraph/memgraph-platform doesn't connect to Memgraph, "Memgraph not detected" message is received

**Comment by gitbuda** [comment]
Something is most likely wrong within the `supervisord.conf`:
```
[program:memgraph]
directory=/usr/lib/memgraph
command=/bin/bash -c "runuser -u memgraph /usr/lib/memgraph/memgraph -- %(ENV_MEMGRAPH)s"
```

Futhermore, the config file `/etc/memgraph/memgraph.conf` has to be somewhere, maybe a quick solution is to Docker mount `/etc/memgraph` and change the config there (in the case multiple flags have to be changed) 🤔

**Comment by andrejtonev** [comment]
Couldn't replicate issue when testing with docker image 2.9.0-memgraph2.9.0-lab2.7.1-mage1.8
Ran `docker run -it -p 7687:7687 -p 3000:3000 -p 7444:7444 -e MEMGRAPH="--storage-properties-on-edges=TRUE --log-level=TRACE" memgraph/memgraph-platform` and 
`docker run -it -p 7687:7687 -p 3000:3000 -p 7444:7444 -e MEMGRAPH="--query-modules-directory=/usr/lib/memgraph/query_modules,/usr/lib/memgraph/user_modules --storage-properties-on-edges=TRUE --log-level=TRACE --log-file=/tmp/mg.log" memgraph/memgraph-platform`
without problems.
note: for the second command, user_modules has to exist

**Comment by matea16** [comment]
I replicated the issue using the following docker-compose file with the memgraph 2.10.0, lab 2.7.1 version:
```
 version: "3"
services:
  memgraph-platform:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg2_lib:/var/lib/memgraph
      - mg2_log:/var/log/memgraph
      - mg2_etc:/etc/memgraph

    environment:
      - MEMGRAPH="--bolt-session-inactivity-timeout=9000  --query-execution-timeout-sec=1000  --log-level=TRACE"

    entrypoint: ["/usr/bin/supervisord"]
    
volumes:
  mg2_lib:
  mg2_log:
  mg2_etc:
```

The issue still persist, every flag except the first one gets ignored

**Comment by matea16** [comment]
The issue was due to this version of Docker not reading the environment variables properly. The issue was fixed and version 3.8 works as expected.

**Comment by antejavor** [comment]
@matea16 Great! I will not close this issue since there is also a config flag missing in the platform image. We need to look into that.

**Comment by gitbuda** [comment]
Closing this issue because it seems that this issue has been fixed 😃

**Comment by matea16** [comment]
Just an update on the topic, creating a `.env` file and listing all of the config flags there seems to solve the issue for all versions. In this case, `docker-compose` file would look like this:
```
version: "3"
services:
  memgraph-platform:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg2_lib:/var/lib/memgraph
      - mg2_log:/var/log/memgraph
      - mg2_etc:/etc/memgraph
    
    env_file:
       - /.env

    entrypoint: ["/usr/bin/supervisord"]
    
volumes:
  mg2_lib:
  mg2_log:
```

with `.env` file containing the config flags:
`MEMGRAPH="--bolt-session-inactivity-timeout=9000  --query-execution-timeout-sec=1000  --log-level=TRACE"`
