### ISSUE TITLE
Is there no way to run the container locally without --interactive?

### ISSUE THREAD

**Issue by CGavrila** [memgraph/memgraph-platform#45]
I am trying to use Memgraph for local development, but I cannot connect to `localhost:3000` without `-it` / `--interactive`. The `Connect Now` button is not active and I cannot connect any other way.

I have tried the following in Docker Compose without success:
```
  memgraph:
    image: memgraph/memgraph-platform:2.6.6-memgraph2.6.0-lab2.5.0
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    volumes:
      - type: bind
        source: ./memgraph
        target: /var/lib/memgraph
```

I must assume that this is by design?
