### ISSUE TITLE
Memgraph Platform Via Helm

### ISSUE THREAD

**Issue by bwhartlove** [memgraph/memgraph-platform#51]
The Memgraph documentation mentions how to deploy Memgraph itself via a Helm chart. Is there something similar available for Memgraph platform? There is, at least as far as I can tell, no documentation on that. I've been having issues with my current deployment where all services _appear_ to be up inside the container, but the front-end says that Memgraph Lab cannot detect Memgraph running in the container.

**Comment by bwhartlove** [comment]
I was able to get passed this. However, my current issue is the inability to create any user via the `-init-file` flag. Even running the `mgconsole < init.cypherl` manually does not work.

**Comment by katarinasupe** [comment]
Hi @bwhartlove, can you tell me which image you used? Memgraph, Memgraph MAGE or Memgraph Platform? How are you passing values to the config settings to Memgraph? Can you explain your process of setting the flags and connecting to a running Memgraph instance? Btw. for quicker and easier communication, [join our Discord server](https://www.discord.gg/memgraph) and ping me there :)

**Comment by bwhartlove** [comment]
Hello! I am using the [Memgraph Platform Image](https://hub.docker.com/layers/memgraph/memgraph-platform/latest/images/sha256-be01525ec48331f52e90b65f536ee6a09df1b48fdb27780ed2a6e9b6ad157fcb?context=explore) and deploying it via a Helm Chart I modified from the Memgraph Helm chart example provided [here](https://memgraph.com/docs/memgraph/reference-guide/deployment/kubernetes).

Since I am trying to run the container as a  non-root user (i.e., as the `memgraph` user), I had to re-roll the image as so:
```
FROM memgraph/memgraph-platform:latest

USER root
COPY supervisord.conf /etc/supervisor/conf.d/
COPY init.cypherl /etc/memgraph/init.cypherl
RUN chown -R memgraph:memgraph /run/ && \
    chown -R memgraph:memgraph /etc/supervisor && \
    chown -R memgraph:memgraph /etc/memgraph && \
    chown -R memgraph:memgraph /var/log/supervisor/
USER 101
CMD ["/bin/bash", "-c", "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf >> /dev/null & echo \"Memgraph Lab is running at localhost:3000\\n\"; while true; do sleep 1; done;"]
```

My supervisord.conf looks as so:
```
[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:lab]
directory=/lab
command=/bin/bash -c "node dist-backend/server.js"

[program:memgraph]
directory=/usr/lib/memgraph
command=/bin/bash -c "/usr/lib/memgraph/memgraph --data-directory=/var/lib/memgraph/data --log-level=DEBUG \ 
                    --bolt-cert-file=/etc/memgraph/ssl/cert.pem --bolt-key-file=/etc/memgraph/ssl/key.pem \ 
                    --init-file=/etc/memgraph/init.cypherl"
```

And my `init.cypherl` file:

```
CREATE USER myuser IDENTIFIED BY "password";
```

This does not appear to pre-populate the database with the user. My intention is to have the container come up so that a user *must* use a username/password to login.

**Comment by katarinasupe** [comment]
Can you send me the modified Helm Chart too?

**Comment by bwhartlove** [comment]
Sure thing. Here's the helm chart (I haven't finished my values file yet, so it's all verbose):
```
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memgraph
  namespace: pipeline
  labels:
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: memgraph-svc
  selector:
    matchLabels:
      app.kubernetes.io/name: memgraph
  podManagementPolicy: OrderedReady
  updateStrategy:
        type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memgraph
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: memgraph
          image: "mycontainerregistry/memgraph-platform-custom"
          securityContext:
            runAsUser: 101
            runAsGroup: 101
          imagePullPolicy: Always
          ports:
            - name: db-port
              containerPort: 7687
            - name: lab-port
              containerPort: 3000
          volumeMounts:
            - name: memgraph-lib-storage
              mountPath: /var/lib/memgraph
            - name: memgraph-log-storage
              mountPath: /var/log/memgraph
      volumes:
        - name: memgraph-lib-storage
          persistentVolumeClaim:
            claimName: memgraph-lib-storage
        - name: memgraph-log-storage
          persistentVolumeClaim:
            claimName: memgraph-log-storage
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: memgraph-svc
  namespace: pipeline
  labels:
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7687
      targetPort: 7687
      protocol: TCP
      name: bolt
  selector:
    app.kubernetes.io/name: memgraph

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: memgraph-lab-svc
  namespace: pipeline
  labels:
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: bolt
  selector:
    app.kubernetes.io/name: memgraph

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memgraph-lab-ingress
  namespace: pipeline
spec:
  rules:
  - host: memgraph.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: memgraph-lab-svc
            port:
              number: 80
        path: /
        pathType: Prefix

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: allow-to-memgraph-lab
  namespace: pipeline
spec:
  ingress:
  - ports:
    - port: 3000
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: memgraph
  policyTypes:
  - Ingress

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memgraph-lib-storage
  namespace: pipeline
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memgraph-log-storage
  namespace: pipeline
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
