### ISSUE TITLE
Memgraph uses wrong settings and MEMGRAPH env vars not propagated correctly

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph-platform#81]
```
  memgraph:
    image: "memgraph/memgraph-platform:latest"
    hostname:
      memgraph
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=TRACE"
```
Not the same as above under k8s (minikube):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: memgraph
  name: memgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memgraph
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/hydrogen-default: "true"
        io.kompose.service: memgraph
    spec:
      containers:
        - env:
            - name: MEMGRAPH
              value: '"--log-level=TRACE --storage-properties-on-edges=true"'
          image: memgraph/memgraph-platform:latest
          name: memgraph
          ports:
            - containerPort: 7687
              hostPort: 7687
              protocol: TCP
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
            - containerPort: 7444
              hostPort: 7444
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/memgraph
              name: mg-lib
            - mountPath: /var/log/memgraph
              name: mg-log
            - mountPath: /etc/memgraph
              name: mg-etc
      hostname: memgraph
      restartPolicy: Always
      volumes:
        - name: mg-lib
          persistentVolumeClaim:
            claimName: mg-lib
        - name: mg-log
          persistentVolumeClaim:
            claimName: mg-log
        - name: mg-etc
          persistentVolumeClaim:
            claimName: mg-etc
status: {}
```
