### ISSUE TITLE
Add flags for Quick connect username and password that can be used in docker-compose

### ISSUE THREAD

**Issue by kgolubic** [memgraph/memgraph-platform#95]
At the moment, if you have a docker-compose file like this one, you can pass a defined username and password to the Lab so that Quick connect works. Adding new environment variables/flags could solve this.

```
version: "3"

services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]
    environment:
      - MEMGRAPH_USER=kruno
      - MEMGRAPH_PASSWORD=pass1

  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
```
